{{- /* SPDX-License-Identifier: Apache-2.0 */ -}}
{{- if eq (include "aetheldb.manageSecret" .) "true" }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "aetheldb.fullname" . }}-secrets
  labels:
    {{- include "aetheldb.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- range $k, $v := .Values.objectStore.credentials }}
  {{ $k }}: {{ $v | quote }}
  {{- end }}
  {{- if and .Values.controlToken.value (not .Values.controlToken.existingSecret) }}
  {{ .Values.controlToken.secretKey }}: {{ .Values.controlToken.value | quote }}
  {{- end }}
{{- end }}
